<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
        /*async返回的是一个promise对象*/
        /*只要await语句后面promise状态变成reject，那么整个async函数会中断执行*/
        async function fn() { //表示异步，这个函数里面有异步任务
            return 'welcome';
            //throw new Error('出错了');

            await Promise.reject('出问题了').catch(err => {
                console.log(err);
            })
            let a = await Promise.resolve('success');
            console.log(a);
        }
        console.log(fn()); //fn()执行以后返回的是promise
        fn().then((res) => {
            console.log(res);
        }, (err) => {
            console.log(err);
        })
    </script>
</body>

</html>